### PR TITLE
Add support for IBatchSpout to redstorm

### PR DESCRIPTION
**Pull request by dinedal**
This is required for basic non-transactional trident spouts defined in jruby.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
thanks @dinedal for the contribution! looks straightforward, I'll review it shortly and merge it. 

Colin

**Comment by dinedal** [comment]
@colinsurprenant Please also review the linear DRPC support I've added.

**Comment by colinsurprenant** [comment]
@dinedal the thing is, Storm 0.8.1 deprecated the LinearDRPC and transactional topologies. We have to see what makes sense now and moving forward. Also @adsummos added lors of stuff to support transactional topologies see  https://github.com/adsummos/redstorm/commit/f2bd64a46ef071825c0d33378d742940b30e509e - I haven't had time to review all this yet in details.

**Comment by dinedal** [comment]
@colinsurprenant Saw his work, looks like he's covered the transactional stuff, but missed the DRPC stuff.

I understand that LinearDRPC is to be deprecated, and it's in my roadmap to work on the Trident classes for Redstorm as well. If you want to comment on my code style / other things to make sure the Trident work I do gets accepted to the main branch easier, please do.

The (I)BatchSpout implementation is going to be used as part of Trident stuff though, to be sure, since it's the non-transactional building block there. Opaque and Transactional spouts need to be done, but BatchSpout works in redstorm native mode, there's just no Trident DSL yet.

**Comment by adsummos** [comment]
I have a use now for the Trident stuff, have you started to work on it yet? If you have, do you have a feature branch you can push out? If not, I'm going to start working on it.

**Comment by colinsurprenant** [comment]
no, haven't look into Trident yet. We should move Trident discussions into issue #46.

**Comment by kb** [comment]
@colinsurprenant Curious if there's a plan in place to merge this work?

cc/ @dinedal

**Comment by colinsurprenant** [comment]
I so badly need to catch up on this. 

«please wait, your call is important to us»   :-P

But seriously, I will reserve time either this weekend or early next week for RedStorm...

**Comment by colinsurprenant** [comment]
Just to let you know I am _now_ catching up on redstorm.

**Comment by colinsurprenant** [comment]
merged your changes locally, working on it.

**Comment by colinsurprenant** [comment]
this is currently merged into the v0.6.5 branch. I did not include your generator code for now. it's an interesting idea but will not test it for 0.6.5. Also, batch bolt support was already added from PR #52. 

Thanks for your contribution!

**Pull request closed without merging**
