### PR TITLE
Got error "java.lang.NoClassDefFoundError: org/jruby/RubyObject" when deploying to remote cluster

### PR DESCRIPTION
**Pull request by Jell**
Problem came from a misconfiguration of markersDirectory.

### CODE REVIEW

**Comment by Xorlev** [comment]
I still get this problem, despite changing the storm version to 0.6.2 in pom.xml and changing build_ruby to 0.6.2 jar. Strange.

**Comment by Jell** [comment]
Hum I actually get the same error the second time I build a jar file and try to upload it to a remote cluster...
Do you have any clues about what might be the problem?

**Comment by Xorlev** [comment]
Other than JRuby 1.6.5.1 and Storm 0.6.2, I didn't change much. Topologies now submit, for example:

storm jar ./target/cluster-topology.jar redstorm.TopologyLauncher cluster examples/simple/word_count_topology.rb

Be careful you don't have a polluted classpath or anything.

**Comment by Jell** [comment]
I solved my problem by setting overWrite to true on the jruby artifact.

**Comment by Jell** [comment]
Ok, the true problem is that the marker for the jruby artifact is in `RedStorm::REDSTORM_HOME/target/dependency-maven-plugin-markers`, but it should be in `TARGET_DIR/target/dependency-maven-plugin-markers`.
I try to find a way to fix that.

**Comment by colinsurprenant** [comment]
Thanks Jell for these patches, I am merging this now.

**Pull request merged**
