### PR TITLE
Avoid forking

### PR DESCRIPTION
**Pull request by iconara**
This is not finished yet, just wanted to show you what I'm working on so don't merge it in, just keep it open. 

I've replaced all shelling out (except for launch, which should probably shell out). Not everything is working yet, I'm still trying to get my head around what is required to be unpacked and bundled into the final jar file.

I rewrote the tasks that installed bundler and then ran bundle with code that uses bundler to figure out the already installed dependencies and copies those to the target dir, but I think there's something not quite working with it because I can't run locally anymore.

Anyway, I'll keep updating this branch (and this pull request) until it's working properly. All comments or suggestions are welcome.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
Niiice, great work!
I'll check to see if I can spot the problem with the jar file packaging. This is something also on my todo list: to better document the layout of the jar file. Also having things working in both local/remote contexts AND in "forked repo dev mode" vs installed gem mode is challenging. Also more on this shortly. 

I'd like to create a branch to merge your changes and play with it a bit. I _think_ it should work if I create a local branch, add your repo as a remote and merge your branch into my branch ... and I am not sure if it will automatically close this pull request... let's try...

Thanks for the initiative!
Colin

**Comment by colinsurprenant** [comment]
few observations:
- in the dependencies, we cannot just copy jruby.jar, we need to fetch jruby-complete-x.y.z.jar for standalone jruby execution from java.
- unpacking: only the jruby-complete-x.y.z.jar need to be unpacked, not all jars

**Comment by colinsurprenant** [comment]
for gems/bundling, i see a few problems and frankly I am not sure what the best approach is. 
- the bundle task presupposes the usage of "./Gemfile" AND that the gems have previously been installed using bundler before running the task. 
- someone forking the repo to work with redstorm will end up with redstorm's own Gemfile which clearly is not what you want for a topology
- someone starting a project with the redstorm gem but with a Gemfile to install redstorm will have the same problem

my original idea was to allow users to specify an alternate Gemfile, let's say examples/simple/Gemfile, specific for the topology your are developing, which would not conflict with any other Gemfile that user might be using for his project but not specific to the topology. This explains all the gymnastics that was in place to reset the Bundler environment so that the gems could be bundled independently from any other bundle in place in the project.

also, your approach suggests you want to just copy the resulting bundled gems into the target dir which might not be such a bad idea but when doing this, the user looses the bundler context and will not be able to use grouping for example using something like this:

``` ruby
require 'bundler'
Bundler.setup(:topology)
```

so the question is, is using Bundler only to specify gems and loosing the Bundler context in the topology execution really a problem? one advantage is that the Bundler gem itself will not be required for the topology.

I haven't checked if it is possible to programmatically perform the equivalent of this alternate location bundling...

**Comment by iconara** [comment]
Ah, `jruby-complete` is of course necessary since we won't be running in a JRuby runtime at the other end, didn't think of that.

The problem I had with the bundle task was that it repeated the work that had already been done (and more slowly). I had to run bundle to get redstorm, and then redstorm ran bundler again. Perhaps just ask people to run bundle with `--path target/gems`? Or give redstorm the names of the groups they want included? (I certainly do not want rspec included, but currently it will be).

Bundler is a bit problematic when it comes to programmatic invocation. It's easy to install gems programmatically, but bundler assumes it's in control, and it gets really annoyed when run in a context where it's already been loaded. I think it can be done, if you dig a bit deeper than I have, but it's definitely not made for it.

Before the latest version of redstorm what we did was that just before the jar task was run we generated a file which set up the load path as it would look within the jar. Then in our topology we checked we were running from within a jar file and set up the load path using the generated file, otherwise we used bundler. I think that trying to get bundler to work within the jar file may not be worth the effort.

I'll see if I can whip up a version that lets you specify a group from your gemfile and have redstorm include just that group in the jar. Redstorm could even have a method equivalent to `Bundler.setup` that does `Bundler.setup` when running normally, but sets up the load path itself when running in a jar.

**Comment by iconara** [comment]
Btw. if you try to run the branch you'll probably notice that pompompom/ivy downloads lots of stupid files like "-sources.jar", ".sha1" and so on. I'm looking for a way to turn this off.

**Comment by colinsurprenant** [comment]
the problem with Bundler is that it saves its state in .bundle so trying to use bundler for two different contexts fails. So running Bundler with `--path target/gems` was basically what the rake task was doing but with the environment resetting to avoid conflicting with other Bundler context. 

I think the idea of using a single Bundler context and grouping the topology gems in a Bundler group would be ok. Then the rake task will need to iterate on these grouped gems and copy them into `target/gems`. That would solve the problem of dealing with the `bundle install` stuff from within the rake task. I like that, lets try it.

**Comment by iconara** [comment]
I've re-added the jruby-complete dependency again (but the unpacking isn't great since the jars to unpack are hard coded).

I also think I've solved the bundle-issue: now I copy all gems, and then I create `red_storm/setup.rb` which sets up the load path, sort of like `bundler/setup.rb` does. It seems to work.

Haven't tried running a JAR in a real cluster yet.

**Comment by colinsurprenant** [comment]
I just found out how to select the specs for specific group(s) (I hardcoded the :topology group here for testing but this could very well be parametrized and default to :redstorm or something like that.

``` ruby
  Bundler.definition.specs_for([:topology]).each do |spec|
    unless spec.full_name =~ /bundler-\d+\.\d+\.\d+/
      FileUtils.cp_r(spec.full_gem_path, "#{RedStorm::GEM_PATH}/gems/#{spec.full_name}")
    end
  end
```

for the unpacking, just jruby-complete needs to be unpacked no other jars...

**Comment by iconara** [comment]
Good one, I'll include the bundler-code in my branch (and make the group an argument to the task -- and making it `:default` by default).

---

It looks like Ivy is confused by the "provided" dependency scope. If I understand it correctly dependencies marked "provided" aren't really needed, in that case you're right, only jruby-complete needs to be unpacked. I'll look into it, I probably have to dig a bit deeper into Ivy because now it's downloading half the internet completely unnecessarily.

**Comment by colinsurprenant** [comment]
- currently, all the jruby-complete dependencies are fetched and copied into `target/dependencies` which is not needed. I do not know how to tweak the config to avoid this... ?
- only jruby-complete need to be unpacked, it is already self contained with all dependencies

```
task :unpack do
  unpack_artifacts = %w[jruby-complete]
```
- the creation of the `setup.rb` file is not needed since the gem home is set with the correct path for both local and jar context. 
- the is a conflict with SLF4J which was not present when using maven... any idea?

``` sh
$ bin/redstorm --1.9 local examples/simple/word_count_topology.rb 
launching java -Djruby.compat.version=RUBY1_9 -cp "/Users/colin/dev/praized/src/internal/redstorm/target/classes:/Users/colin/dev/praized/src/internal/redstorm/target/dependency/*" -Djruby.gem.home=/Users/colin/dev/praized/src/internal/redstorm/target/gems/gems redstorm.TopologyLauncher local examples/simple/word_count_topology.rb
SLF4J: The requested version 1.5.8 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
```

**Comment by colinsurprenant** [comment]
I have never used Ivy but it seems we can disable transitive dependency using transitive="false" ex.:

``` xml
<dependencies>  
   <dependency org="org.hibernate" name="hibernate-core"
               rev="3.3.1.GA" conf='..'
               transitive="false" /> 
</dependencies>
```

Would it be possible to pass such an option to our jruby-complete dependency declaration? This should avoid fetching the artifacts which are already packaged in the jruby-complete jar. 

For the SLF4J conflict I can't figure out why `slf4j-api-1.6.3` and `slf4j-log4j12-1.5.8` are fetched with conflicting versions. Using the old maven task, both were at version 1.5.8. Any idea?

**Comment by iconara** [comment]
Sorry, been very busy the last few days. I'll try to get your pompompom suggestion merged in, and see if I can find anything else in the Ivy docs. I don't think the problem is the transitivity (although in this case it would fix the symptom), but that Ivy doesn't care that the dependencies of jruby-complete are marked as "provided". It might be that since those JARs might be needed for compilation it thinks it needs to download them. I think that the JRuby guys have actually done the wrong thing in their POM, since the dependencies are bundled into the main JAR they are not "provided" since "provided" means that the dependency is provided by a separate runtime (like the servlet API would be provided by Tomcat). Not that we can change it, but it would at least explain the oddities. Bla bla bla. Anyway, transitive=false would at least remove the symptom.

**Comment by colinsurprenant** [comment]
Good stuff, we're getting there! I think at this point the only other issue is the SLF4J version conflict. It does not seem to affect the runtime, I was able to launch a topology in local mode and it seems to works ok. Do you have any idea on this?

**Comment by colinsurprenant** [comment]
I just pushed the last changes in the avoid_forking branch. for SLF4J I hardcoded an extra dependency to stop the conflict warning. Everything else is pretty good at this point. I'll open a few tickets for a few improvements we can look into eventually. Also need to update the README to document all this. 

Thanks you for your contribution and initiating all this, its a very good improvement.

**Pull request closed without merging**
