### PR TITLE
transactional topologies

### PR DESCRIPTION
**Pull request by adsummos**
Added support for transactional topologies with transactional bolts and spouts.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
Thanks for your contribution! This is good stuff. I will review this shortly and see if we can make a release for it. I'd like to have some way to test this prior to a release with maybe an example transactional topology in `examples/simple` and ideally a transactional topology integration test in `test/integration` and `test/topology`.

**Comment by adsummos** [comment]
I doubt we will have much time in the near term to add tests to the gem because we are very busy working on the project based on these changes, but if I get some extra time I will try

**Comment by colinsurprenant** [comment]
fair enough. I don't want to spend too much time on this either because transactional topologies are deprecated as of Storm 0.8 in favor of trident topologies...

**Comment by adsummos** [comment]
are they? The trident topologies don't seem to do quite the same thing, I don't think we could use them for our process

**Comment by colinsurprenant** [comment]
Yup. See 0.8.1 changelog https://github.com/nathanmarz/storm/blob/master/CHANGELOG.md "Deprecated LinearDRPCTopologyBuilder, TimeCacheMap, and transactional topologies" ...

**Comment by adsummos** [comment]
well, these changes should make the step to trident topologies a little easier

**Comment by colinsurprenant** [comment]
merged your changes locally, working on it.

**Comment by colinsurprenant** [comment]
I merged your changes in the v0.6.5 branch. I did not include the helpers.rb and MurmurHash.java code. I added constructor fields support on the classes which implements IComponent for future integration into the DSL. 

Thanks again for your contribution!

**Comment by adsummos** [comment]
oops, I didn't mean to include those. It was difficult to get access to that code without including it in our branch of redstorm. There doesn't seem to be a good way to include arbitrary jars/java code

**Pull request closed without merging**
